### ISSUE TITLE
[suggestion] Re-work the mod to do the upgrades researchable

### ISSUE THREAD

**Issue by frenchiveruti** [pyroinfernia/Roboport_Quick_Charge#1]
So, that way, the mod will instead of force the player to spend more resources on each roboport, but instead research the technology to upgrade them

**Comment by pyroinfernia** [comment]
Thanks for your feedback. I'm in the process of doing that. I ran into a lot of limitations of the current Factorio API that slowed me down and had to think of a few workarounds to get done what I wanted to accomplish.

**Comment by frenchiveruti** [comment]
Ah ok, well, it's good to know that it's part of the idea to get that as a research.
The API allows you to edit actually placed entities via researching?
That could be a way to do it, maybe check out the tech from the inserters that allows them to have more items per action?

**Comment by pyroinfernia** [comment]
v0.2.0 released. Let me know if you encounter any problems or bugs.
